#───────────────────────────────────────────────────────────────
#Developed by @jams2blues – ZeroContract Studio
#File:    .github/workflows/ci.yml
#Rev :    r1    2025‑09‑05
#Summary: lint‑test‑build matrix Node 20 & 22; status for branch protection
#───────────────────────────────────────────────────────────────
name: CI

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  build‑test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x]   # Invariant I29
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack & Yarn 4.9.1
        run: |
          corepack enable
          corepack prepare yarn@4.9.1 --activate

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies (immutable)
        run: yarn install --immutable --inline-builds

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build --filter=!**/summarized_files/**

      - name: Upload build artefact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.node-version }}
          path: .next

#What changed & why: provides required “CI” status check for branch protection
