# Developed by @jams2blues – ZeroContract Studio
# File:    .yarnrc.yml
# Rev :    r557   2025‑09‑05
# Summary: drop repo‑wide enableImmutableInstalls guard; CI uses flag

# ───────── linker & cache ────────────────────────────
nodeLinker: node-modules
enableGlobalCache: true
nmHoistingLimits: workspaces

# ───────── reproducibility snapshot ─────────────────
installStatePath: .yarn/install-state.gz

# NOTE
# • We removed `enableImmutableInstalls:true` so a fresh clone
#   (or accidental lockfile deletion) can still run `yarn install`
#   locally and regenerate **yarn.lock**.
# • CI and Codex already invoke:
#       yarn install --immutable --inline-builds
#   which enforces the lock‑guard during automated runs.
# • After a local reinstall, commit the regenerated yarn.lock.

# ───────── package edge‑case patches ────────────────
packageExtensions:
  "@taquito/beacon-wallet@21.0.4":
    peerDependenciesMeta:
      "@testing-library/dom":
        optional: true
      react:
        optional: true
      react-dom:
        optional: true

# EOF
