# Developed by @jams2blues – ZeroContract Studio
# File:    .yarnrc.yml
# Rev :    r553   2025‑09‑03
# Summary: CI‑safe Yarn 4 pin + install‑state hints for Codex

# ───────── linker & cache ────────────────────────────
nodeLinker: node-modules            # classic flat node_modules – avoids PnP edge‑cases
enableGlobalCache: true             # re‑uses Codex layer cache, speeds subsequent runs
nmHoistingLimits: workspaces         # smaller node_modules footprint on CI

# ───────── reproducibility guards ────────────────────
immutableInstalls: true             # build fails on lock drift
installStatePath: .yarn/install-state.gz  # explicit path – silences “missing state file”

# ───────── Yarn version pin (Invariant I21) ──────────
yarnPath: .yarn/releases/yarn-4.9.1.cjs  # pinned Corepack shim

# ───────── package edge‑case patches ────────────────
packageExtensions:
  "@taquito/beacon-wallet@21.0.4":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
      "@testing-library/dom":
        optional: true

# EOF
