# Developed by @jams2blues – ZeroContract Studio
# File:    .yarnrc.yml
# Rev :    r554   2025-09-05
# Summary: drop yarnPath (Codex ENOENT); pin via Corepack

# ───────── linker & cache ────────────────────────────
nodeLinker: node-modules
enableGlobalCache: true
nmHoistingLimits: workspaces

# ───────── reproducibility guards ────────────────────
immutableInstalls: true
installStatePath: .yarn/install-state.gz

# ───────── Yarn version pin (Invariant I21) ──────────
# Yarn is now activated by Corepack inside scripts/codex-setup.sh,
# so a local release file is no longer required (fixes Codex ENOENT).

# ───────── package edge-case patches ────────────────
packageExtensions:
  "@taquito/beacon-wallet@21.0.4":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
      "@testing-library/dom":
        optional: true

# EOF
