# Developed by @jams2blues – ZeroContract Studio
# File:    .yarnrc.yml
# Rev :    r555   2025-09-05
# Summary: fix unsupported key (immutableInstalls → enableImmutableInstalls)

# ───────── linker & cache ────────────────────────────
nodeLinker: node-modules
enableGlobalCache: true
nmHoistingLimits: workspaces

# ───────── reproducibility guards ────────────────────
enableImmutableInstalls: true          # Yarn 4 key — replaces deprecated immutableInstalls
installStatePath: .yarn/install-state.gz

# ───────── package edge-case patches ────────────────
packageExtensions:
  "@taquito/beacon-wallet@21.0.4":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
      "@testing-library/dom":
        optional: true

# EOF
