# Developed by @jams2blues – ZeroContract Studio
# File:    .yarnrc.yml
# Rev :    r554   2025-09-05
# Summary: Yarn 4 CI settings — removed static yarnPath to fix Codex ENOENT

# ───────── linker & cache ────────────────────────────
nodeLinker: node-modules            # classic flat node_modules – avoids PnP edge-cases
enableGlobalCache: true             # reuse Codex layer cache
nmHoistingLimits: workspaces        # smaller footprint

# ───────── reproducibility guards ────────────────────
immutableInstalls: true
installStatePath: .yarn/install-state.gz        # silences “missing state file”

# ───────── package edge-case patches ────────────────
packageExtensions:
  "@taquito/beacon-wallet@21.0.4":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
      "@testing-library/dom":
        optional: true

# Note: yarnPath removed — Corepack activates Yarn dynamically.
# EOF
