name: Build & Deploy Explore Feed

on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'  # every 1 minutes

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Detect repo root
        id: root
        shell: bash
        run: |
          set -e
          if [ -f scripts/exploreFeed.mjs ]; then
            echo "dir=." >> $GITHUB_OUTPUT
          elif [ -f zerounbound/scripts/exploreFeed.mjs ]; then
            echo "dir=zerounbound" >> $GITHUB_OUTPUT
          else
            echo "::error::exploreFeed.mjs not found in repo"; ls -la; exit 1
          fi

      - name: Generate feed (mainnet)
        shell: bash
        working-directory: ${{ steps.root.outputs.dir }}
        run: |
          set -e
          FEED_OUT_DIR="$GITHUB_WORKSPACE/feed-dist" node scripts/exploreFeed.mjs --network=mainnet --page-size=100 --max-pages=120

      - name: Generate feed (ghostnet)
        shell: bash
        working-directory: ${{ steps.root.outputs.dir }}
        run: |
          set -e
          FEED_OUT_DIR="$GITHUB_WORKSPACE/feed-dist" node scripts/exploreFeed.mjs --network=ghostnet --page-size=100 --max-pages=60

      - name: Add .nojekyll
        run: |
          mkdir -p feed-dist
          touch feed-dist/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: feed-dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
