name: Build & Deploy Explore Feed

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate feed (mainnet)
        run: |
          set -e
          if [ -f scripts/exploreFeed.mjs ]; then SCRIPT="scripts/exploreFeed.mjs"; elif [ -f zerounbound/scripts/exploreFeed.mjs ]; then SCRIPT="zerounbound/scripts/exploreFeed.mjs"; else echo "feed script not found"; exit 1; fi
          FEED_OUT_DIR="$GITHUB_WORKSPACE/feed-dist" node "$SCRIPT" --network=mainnet --page-size=100 --max-pages=120

      - name: Generate feed (ghostnet)
        run: |
          set -e
          if [ -f scripts/exploreFeed.mjs ]; then SCRIPT="scripts/exploreFeed.mjs"; elif [ -f zerounbound/scripts/exploreFeed.mjs ]; then SCRIPT="zerounbound/scripts/exploreFeed.mjs"; else echo "feed script not found"; exit 1; fi
          FEED_OUT_DIR="$GITHUB_WORKSPACE/feed-dist" node "$SCRIPT" --network=ghostnet --page-size=100 --max-pages=60

      - name: Add .nojekyll
        run: |
          mkdir -p feed-dist
          touch feed-dist/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: feed-dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
